<?php
// Auto-generated by install.php on 2026-09-07 04:46:14
return [
    'db_host'    => 'localhost;port=3307',
    'db_name'    => 'edesk_stationery',
    'db_user'    => 'root',
    'db_pass'    => '',
    'db_charset' => 'utf8mb4',
    'shop_name'  => 'eDESK STATIONERY',
    'installed'  => true,
];
