<?php
// Auto-generated by install.php on 2026-08-23 22:52:13
return [
    'db_host'    => '127.0.0.1;port=3307',
    'db_name'    => 'edesk_stationery',
    'db_user'    => 'root',
    'db_pass'    => '',
    'db_charset' => 'utf8mb4',
    'shop_name'  => 'EDESK STATIONERY',
    'installed'  => true,
];
